name: Build and Deploy Code
# if you want it to run on both push and pull-requesut on: [push, pull_request]
on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        